name: Run Registry Tests 🧪

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 📥
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # Ensures submodules are also checked out

      - name: Setup Node.js 🌐
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Update Git Submodules 🔄
        run: |
          make update-fixtures
          make submodule-status

      - name: Install and Build v1 🏗️
        run: |
          cd v1
          yarn install
          yarn symlink
          yarn build
          yarn symlink

      - name: Install and Build v2 🏗️
        run: |
          cd v2
          yarn install
          yarn symlink
          yarn build
          yarn symlink

      - name: Test @chain-registry/keplr 🔍
        run: cd v1/packages/keplr && yarn test
      
      - name: Legacy Test @chain-registry/cosmostation 🔍
        run: cd v1/packages/cosmostation && yarn test
      
      - name: Test @chain-registry/v2-cosmostation 🔍
        run: cd v2/packages/cosmostation && yarn test
      
      - name: Legacy Test @chain-registry/utils 🔍
        run: cd v1/packages/utils && yarn test
      
      - name: Test @chain-registry/utils 🔍
        run: cd v2/packages/utils && yarn test
      
      - name: Legacy Test @chain-registry/client 🔍
        run: cd v1/packages/client && yarn test
        
      - name: Test @chain-registry/client 🔍
        run: cd v2/packages/client && yarn test
        
      - name: Test @chain-registry/workflows 🔍
        run: cd v2/workflows/workflows && yarn test

      - name: Test @chain-registry/cli 🔍
        run: cd v2/workflows/cli && yarn test